### ISSUE TITLE
Unable to use keys inside text input

### ISSUE THREAD

**Issue by joe-chelladurai** [r4fun/keys#11]
I've been trying to use shortcut keys while the cursor is inside the text input, but it doesn't work. It does work once I'm outside the textbox. Is there a way to fix this issue?

I found this to be a helpful resource to figure out a solution. I wish I knew more javascript to contribute.
https://github.com/ccampbell/mousetrap/tree/master/plugins/global-bind

**Comment by tylerlittlefield** [comment]
Hey @meshach-joe thanks for providing the link to the plugin. I've made a branch that might be what you're looking for. I'll need to test it out a bit more before I merge it to master and submit to CRAN. For the time being, you can give it a spin with:

```r
# install the branch with global bind plugin
# devtools::install_github("r4fun/keys", ref = "global-bind")

library(shiny)
library(keys)

hotkeys <- c(
  "1", 
  "command+shift+k", 
  "up up down down left right left right b a enter"
)

ui <- fluidPage(
  useKeys(),
  keysInput("keys", hotkeys, global = TRUE),
  textInput("txt", "txt input")
)

server <- function(input, output, session) {
  observeEvent(input$keys, {
    print(input$keys)
  })
}

shinyApp(ui, server)
```

Note that setting `global = TRUE` is only available in the `keysInput` function. So I haven't written anything to allow global key bindings with something like `addKeys`. Still thinking about how it should work.

**Comment by joe-chelladurai** [comment]
Awesome! This works very well and thanks for the very quick response.

This may be a related issue, so when I tried it with ```shinyAce::aceEditor```, it didn't work:

```
library(shiny)
library(keys)

hotkeys <- c(
  "1", 
  "ctrl+shift+k", 
  "up up down down left right left right b a enter"
)

ui <- fluidPage(
  useKeys(),
  keysInput("keys", hotkeys, global = TRUE),
  textInput("txt1", "txt input"),
  aceEditor("txt", "txt input",
            height = "50px")
)

server <- function(input, output, session) {
  observeEvent(input$keys, {
    print(input$keys)
  })
}

shinyApp(ui, server)
```

https://github.com/trestletech/shinyAce

**Comment by tylerlittlefield** [comment]
Happy to hear the `textInput` is working! The `shinyAce` example you provided is also working on my end. Could you clarify what the issue is?

**Comment by joe-chelladurai** [comment]
I just found that it was an error on my end. So sorry! It works with ```shinyAce```

Thanks for this wonderful package!

**Comment by tylerlittlefield** [comment]
No worries! I'll keep this issue open until I merge the `global-bind` branch to master.

**Comment by vgherard** [comment]
Hi! I was wondering whether you have any update on the `global-bind` branch. I'm depending on it for a personal package (works like charm, thanks) and was considering submitting to CRAN at some time.

Thanks, 
Valerio.

**Comment by tylerlittlefield** [comment]
@vgherard I have admittedly forgot to merge this to master. Let me re-review my work, merge to master and get this on CRAN. I'll update this thread on any status updates. Neat package by the way!

**Comment by tylerlittlefield** [comment]
Okay, this feature is on its way to CRAN in [`keys v0.1.1`](https://cran.r-project.org/web/packages/keys/index.html)!

**Comment by vgherard** [comment]
Great, thank you so much!

> Okay, this feature is on its way to CRAN in [`keys v0.1.1`](https://cran.r-project.org/web/packages/keys/index.html)!

**Comment by mayeulk** [comment]
@vgherard @tylerlittlefield
 Hi, the thread for this issue "[Unable to use keys inside text input](https://github.com/r4fun/keys/issues/11#top)" helped me solve an issue with radio buttons, in which
 keysInput("keys",... , global = TRUE) 
is needed otherwise, after selecting a radio button, keysInput is inactive unless we click elsewhere in the page background.
I'm writing this comment as I believe the help for   keysInput(,... , global = TRUE)  should be updated

**Comment by mayeulk** [comment]
I take this opportunity to thank the authors of this package, and people who wrote in this issue https://github.com/r4fun/keys/issues/11 (which helped me fix a bug in my app, which works almost only with keys - https://gricad-gitlab.univ-grenoble-alpes.fr/kauffmma/quizplayr)
