### ISSUE TITLE
does this package work?

### ISSUE THREAD

**Issue by rcorty** [r4fun/keys#16]
I copied the code from the readme into an rshiny project and couldn't get these sort of "hello world" type examples to work as expected. Is there any rshiny app currently active online that can demonstrate the correct use and behavior?

**Comment by tylerlittlefield** [comment]
The `README.md` example is working for me. Can you provide a reproducible example that doesn't work?

**Comment by tylerlittlefield** [comment]
Closing. If a reproducible example is provided, I will reopen.
