### ISSUE TITLE
Make package available via conda

### ISSUE THREAD

**Issue by hechth** [r4fun/keys#17]
It would be great to have this package also available via the `conda` ecosystem, not only CRAN. Would it be possible to host the package via [conda-forge](https://conda-forge.org/docs/maintainer/adding_pkgs.html)? Just let me know if you would need any help with this or preferred if I would take care of this.

Thanks!

**Comment by tylerlittlefield** [comment]
I have no experience with `conda-forge` but it would be really cool to see this package available there. If you want to give it a go, please do! PRs are open.

**Comment by hechth** [comment]
Cool, feel free to assign this to me as an issue, just to keep track of things. Would you be willing to be listed as a maintainer?

**Comment by tylerlittlefield** [comment]
Sure! Happy to be listed as a maintainer. Out of curiosity, can packages be published to `conda-forge` with github actions? I saw [this](https://conda-forge.org/docs/maintainer/conda_forge_yml.html#) and am wondering how subsequent updates to `conda-forge` would work.

Also, feel free to modify this packages DESCRIPTION file to include yourself as contributor if you'd like.

**Comment by hechth** [comment]
I don't know how this exactly works with conda forge, I know that bioconda for example is updated automatically upon creating a new release on GitHub. I thought `conda-forge` might be preferable as a channel as it is more generic than bioconda. I'll see how it works with automatic updates there.

**Comment by hechth** [comment]
PR is open at https://github.com/conda-forge/staged-recipes/pull/17424

**Comment by mfansler** [comment]
> Out of curiosity, can packages be published to `conda-forge` with github actions? I saw [this](https://conda-forge.org/docs/maintainer/conda_forge_yml.html#) and am wondering how subsequent updates to `conda-forge` would work.

@hechth @tyluRp The standard Conda Forge recipe template for R packages is to work downstream from CRAN. Conda Forge has an hourly GitHub Workflow that checks CRAN for new releases and then automatically generates PRs on the corresponding feedstocks. New feedstocks now default to auto-merging bot-PRs, so under typical circumstances pushing to CRAN propagates to Conda Forge automatically.

**Comment by tylerlittlefield** [comment]
Closing now that the PR is merged. Thanks again @hechth for setting this up. I'll update the README later today to add the conda badge.
