### ISSUE TITLE
Add "hacktoberfest" as a repo topic

### ISSUE THREAD

**Issue by ColinFay** [r4fun/keys#4]
Hey, 

As #1 is tagged "hacktoberfest", you'd also need to add "hacktoberfest" as a repo topic to make it valid ;) 

> Maintainers of a repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

Could you turn this on?

Cheers, 
Colin

**Comment by tylerlittlefield** [comment]
Thanks! I've added this topic to the repo 👍
